# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5975941859608bf2e20933567af2077df6f89e77c38552081a49c740a7a4b651fdac1f1f349e974aae761210e25689d8f299228693a39dadadccb1d7457c1679

test:
  secret_key_base: 10d66189554ea796f28f7c28ea565dbd6693ae86192b7a8d4bb2fb0707a2a3fcd1ed80d6b1a2d66350c9c58afaf58edee1036829f7d6d1c2c7e1cbb6f95be303

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
